Added default pid feature
ZunamiLab/ZunamiProtocol pull request #117
Opened 2022-02-28 19:35 UTC by senichevalexey

This functionality is necessary for the correct work of such
functions as completeDeposits and completeWithdrawals

2022-03-01 21:31 UTC, MioGreen requested changes

2022-03-01 21:31 UTC, MioGreen commented on .solhint.json
> +        "compiler-version": ["error", "0.8.0"]
уже в пору 0.8.12  ставить

2022-03-01 21:31 UTC, MioGreen commented on contracts/Zunami.sol
> +    uint256 public defaultPoolID;
Солидити ближе в JS - лучше  defaultPoolId

2022-03-01 21:31 UTC, MioGreen commented on contracts/Zunami.sol
> +        _grantRole(OPERATOR_ROLE, _newOperator);
мда

2022-03-02 08:50 UTC, senichevalexey commented on .solhint.json
> +        "compiler-version": ["error", "0.8.0"]
это сделано для того чтобы solhint не ругался на смарты openzeppelin, так как у них версия 0.8.0

2022-03-02 08:52 UTC, senichevalexey commented on contracts/Zunami.sol
> +        _grantRole(OPERATOR_ROLE, _newOperator);
согласно официальной документации _setupRole можно использовать только в конструкторе

2022-03-02 09:36 UTC, senichevalexey commented on contracts/Zunami.sol
> +    uint256 public defaultPoolID;
поправил

2022-03-02 12:36 UTC, MioGreen approved these changes

2022-03-02 12:38 UTC, merged