Added set default pid for withdraw feature
ZunamiLab/ZunamiProtocol pull request #122
Opened 2022-03-07 21:09 UTC by senichevalexey

2022-03-07 21:16 UTC, MioGreen requested changes

2022-03-07 21:16 UTC, MioGreen commented on contracts/Zunami.sol
> +    uint256 public defaultDepositPoolId;
давай писать defaultDepositPid  - мы вроде pid везде используем

2022-03-08 09:21 UTC, fextr approved these changes

2022-03-09 08:14 UTC, MioGreen approved these changes

2022-03-09 08:14 UTC, merged