Feat/profitable pool
ZunamiLab/ZunamiProtocol pull request #35
Opened 2021-08-13 19:33 UTC by smartdev0725

2021-08-17 07:59 UTC, senichevalexey requested changes

2021-08-17 07:59 UTC, senichevalexey commented on contracts/ProfitablePool.sol
> +}
it is good practice to put interfaces in separate files as they may be needed in different smart contracts

2021-08-17 07:59 UTC, senichevalexey commented on contracts/ProfitablePool.sol
> +      rewards = type(uint).max / rewards;
it is a convenient way to use a single variable, but it makes the code less clear

2021-08-17 07:59 UTC, senichevalexey commented on test/ProfitablePool.test.js
> +            console.log('Max reward pool address:', profitableAddress.toString());
tests must have some kind of verification  or assertion, otherwise it will not be possible to signal that some piece of code has broken this functionality

2021-08-17 09:47 UTC, firmamentum requested changes

2021-08-17 09:47 UTC, firmamentum commented on test/ProfitablePool.test.js
> +    const convexPoolArray = [
If possible, please make this a json file which can be imported to the code, so that it can also be re-used in other places.

2021-08-17 09:47 UTC, firmamentum commented on test/ProfitablePool.test.js
> +        profitablePool = await profitablePool.deploy();
Await for the contract to be deployed i.e. `await(await profitablePool.deploy()).deployed()` that way you don't get any unnecessary errors when calling the contract functions.

2021-08-19 12:17 UTC, typicalbuster commented
Replace all compute operations with SafeMath operations.

2021-09-23 13:25 UTC, closed without merging