Staking bugfix
ZunamiLab/ZunamiProtocol pull request #70
Opened 2022-01-08 01:22 UTC by bitok228

2022-01-10 12:50 UTC, senichevalexey requested changes

2022-01-10 12:50 UTC, senichevalexey commented on contracts/ZunStaker.sol
> +    uint256 public lastRewardBlock = 0; // change in prod
а что значит "change in prod"?

2022-01-10 12:50 UTC, senichevalexey commented on contracts/ZunStaker.sol
> +    ) public view returns (Deposit[] memory) {
здесь у параметров есть отступы

2022-01-10 12:50 UTC, senichevalexey commented on contracts/Zunami.sol
> +    returns (uint256)
а здесь у параметров нет отступов, надо все же тебе настроить код стайл

2022-01-10 12:50 UTC, senichevalexey commented on contracts/tokens/veZUN.sol
> +contract veZUNtoken is Context, Ownable, ERC20 {
Решили же вроде изменить название?

2022-01-11 07:23 UTC, bitok228 commented on contracts/tokens/veZUN.sol
> +contract veZUNtoken is Context, Ownable, ERC20 {
нет, это veZUN governance токен а есть еще wZLP токен (wrapped ZunamiLP)

2022-01-12 18:29 UTC, senichevalexey approved these changes

2022-01-12 18:29 UTC, merged