emergency from strategy
ZunamiLab/ZunamiProtocol pull request #90
Opened 2022-01-28 10:38 UTC by bitok228

2022-01-28 10:49 UTC, senichevalexey requested changes

2022-01-28 10:49 UTC, senichevalexey commented on contracts/strategies/CurveConvexStrat.sol
> +    function emergency() external onlyOwner {
лучше по-другому назвать функцию

2022-01-28 10:49 UTC, senichevalexey commented on contracts/strategies/CurveConvexStrat.sol
> +                _msgSender(),
вывод происходит на кошелек владельца? Может лучше на Zunami.sol выводить?

2022-01-28 13:13 UTC, bitok228 commented on contracts/strategies/CurveConvexStrat.sol
> +                _msgSender(),
а как потом с Zunami выводить? Это же и так вывод на случай если Zunami сломается

2022-01-28 13:14 UTC, bitok228 commented on contracts/strategies/CurveConvexStrat.sol
> +    function emergency() external onlyOwner {
inCaseFundsStuck

2022-01-28 14:11 UTC, bitok228 commented on contracts/strategies/CurveConvexStrat.sol
> +                _msgSender(),
лучше emegrency сразу на овнера выводить

2022-01-28 14:11 UTC, bitok228 commented on contracts/strategies/CurveConvexStrat.sol
> +                _msgSender(),
это на случай если вообще все сломается

2022-02-15 22:50 UTC, MioGreen commented on contracts/strategies/CurveConvexStrat2.sol
> +        pool3.remove_liquidity(pool3LP.balanceOf(address(this)), minAmounts);
Выведенный дополнительный токен а такх CRV и CVX, планируется выводить отдельно через function inCaseTokenStuck(IERC20Metadata _token) ?

2022-02-16 10:24 UTC, closed without merging